sudo: require
language: generic
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2
services:
  - docker
before-install:
  - chmod +x ./continous_deployment.sh

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./deploy.sh; fi'

notifications:
  email: false
