version: "3.7"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "5000:5000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    ports:
      - "3000:3000"
